### ISSUE TITLE
[Bug] Invalid authentication by using Andoid app

### ISSUE THREAD

**Issue by ufozone** [ngocjohn/vehicle-info-card#65]
### Short summary 📝

Invalid authentication for requested URL '/api/template' by using Andoid app

### Detailed description 📋

I use the Home Assistant Andoid app ([Play Store Link](https://play.google.com/store/apps/details?id=io.homeassistant.companion.android)) on several devices.

Since I have been using the Vehice Card, the logs of my Home Assistant instance have flooded with the following logs:
`Login attempt or request with invalid authentication from .... Requested URL: '/api/template'`

I have tried different users on the devices (the dashboards load correctly) and also completely wiped the app on one device. Unfortunately, the result remains the same.

As soon as I remove the card from my dashboard and update the dashboards on the Android devices, the log floods stop.

What other information can be helpful in finding the cause?

### Version 📌

v1.3.1

### Environment 🌐

Home Assistant Andoid App Version 2024.7.3-full

### Logs and screenshots 📂

If I use the normal login with user and password:
```log
2024-09-21 16:26:47.489 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.20.133 (192.168.20.133). Requested URL: '/api/template'. (Mozilla/5.0 (Linux; Android 8.1.0; rk3288 Build/OPM8.181105.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/128.0.6613.146 Safari/537.36 Home Assistant/2024.7.3-13278 (Android 8.1.0; rk3288))
```

When I use [trusted_networks](https://www.home-assistant.io/docs/authentication/providers/#trusted-networks) authentication, I get the same number of logs with the following content:
```log
2024-09-21 16:22:24.322 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/api/__init__.py", line 482, in post
    tpl = _cached_template(data["template"], request.app[KEY_HASS])
                           ~~~~^^^^^^^^^^^^
KeyError: 'template'
```

**Comment by ngocjohn** [comment]
> I have tried different users on the devices (the dashboards load correctly) and also completely wiped the app on one device. Unfortunately, the result remains the same.
> 
> As soon as I remove the card from my dashboard and update the dashboards on the Android devices, the log floods stop.
> 
> What other information can be helpful in finding the cause?

Have you tried logging out of the android device, and logging back in? Strange that it works on other devices...

**Comment by ufozone** [comment]
Yes, I have logged out and logged back in to the app on all devices. Even with different users.

As far as I can tell, it always occurs in the Android app. All devices (five in number) with the app cause the problem. If I call up Home Assistant on the devices via the browser, it works.

The logs also appear if the app is only running in the background on the mobile devices. I am afraid that the card cannot access the `auth_token` at that time.

Very strange bug.

**Comment by ufozone** [comment]
I have recorded a HAR (L[ink to HAR analyzer](https://toolbox.googleapps.com/apps/har_analyzer/)) to be able to trace the requests and responses:
[192.168.10.17_Archive [24-09-22 11-05-15].har.json](https://github.com/user-attachments/files/17088962/192.168.10.17_Archive.24-09-22.11-05-15.har.json)

The Bearer token in auth header is correct (other cards are using the same successfully with requests against the API).

Why is the card spamming so hard (look at the time intervals)? The API endpoint is certainly bothered by the fact that the request body is empty.

**Comment by ngocjohn** [comment]
Yeah, I'll try to rewrite the template methods for custom buttons..
